### ISSUE TITLE
Past Events

### ISSUE THREAD

**Issue by way0utwest** [sqlcollaborative/DataSaturdays#108]
With the first event being completed, we need a way to clear up our list.

Of course, being a slow learner, I neglected to create a branch before added a /past.html. I did update the nav to add a link to the past page, as well as ensuring the "Events" nav goes to /index.html#events.

I moved the Guatemala event from index.html to past.html, but we likely need to have a good process for this.

**Comment by spaghettidba** [comment]
I think the datatable can be filtered, but I would have to study how to do that.

**Comment by SQLDBAWithABeard** [comment]
New data driven process from #149 will automatically move events into past events on the next build of the site
