### ISSUE TITLE
Seed funding

### ISSUE THREAD

**Issue by gavincampbell** [sqlcollaborative/DataSaturdays#13]
I have heard that for DevOpsDays, profitable events use part of their surplus to provide "bridging" loans to new events, so that they can pay early bills - venue etc. - before their sponsors pay them, which as we all know can take a long time. This is organised in a peer-to-peer way rather than being centrally brokered. I've often thought such a model would be helpful, if unlikely, for SQL Saturday.

**Comment by stephlocke** [comment]
A fund raising route examined for satRdays is https://crowdfunding.lfx.linuxfoundation.org/?filter=#events

**Comment by bweissman** [comment]
isn't the main issue that should probably be adressed that sponsors should just pay faster? which you can "enforce" by "we don't promote you before payment" etc?

**Comment by steverezhener** [comment]
@bweissman , you are right here - no money, no show. I think the main idea here was having some funds to allow creation of brand new events. That being said, what is more important than money is having a mentor, somebody with experience that can do the hand holding.

**Comment by andrekamman** [comment]
We discussed this internally regarding the Dutch event and decided against it. Sponsors pay to get exposure in a target market. They would not be amused if they suddenly see their budget spent elsewhere. We keep a healthy reserve to make sure we can pre-pay things and also be ready for unexpected things. But we do make sure the sponsors money is used.

This doesn't stop other types of support like crowd funding and mentoring obviously, but I would be carefull with moving money between events

**Comment by DataHubert** [comment]
Same thing here in Poland. Sign sponsorship contract, pay and then appear in SM's, announcements, etc. And plan few years ahead :-)

**Comment by gavincampbell** [comment]
Hi Andre, I think you're right. The difference with some events that do this is that they charge people to attend, so the surplus isn't necessarily from sponsor funding.
