### ISSUE TITLE
Data Saturday Southwest US

### ISSUE THREAD

**Issue by desertislesql** [sqlcollaborative/DataSaturdays#130]
May 15, 2021
Virtual Event
Mountain Standard Time Zone

This Data Saturday Event is being jointly developed by the Albequerque Data Platform Users Group, Arizona Data Platform Users Group,  and the Santa Fe Data Platform Users Groups.  This event will include sessions on many Microsoft Data Platform related topics.

We encourage interested speakers to submit sessions via Sessionize using this link

In particular we would like to encourage speakers local to the southwest region of the United States to submit 60 minute sessions.

For any additional questions, please contact us at 

Regards,

Adrian Mee
Chris Hyde 
Ginger Grant

**Comment by way0utwest** [comment]
Need a few things here:
- Sessionize URL
- regsitration url, or is there no registration?
- contact email (or you can use the data saturday one

**Comment by DrJekyll325** [comment]
Please remove the section that says "SPONSORS If you want to sponsor this event get in touch with the organizers" from the event landing page.  We aren't seeking or accepting any sponsors for the event.

**Comment by way0utwest** [comment]
PR #132 comments out sponsors

**Comment by SQLDBAWithABeard** [comment]
Event page has been created
