### ISSUE TITLE
Data.Toboggan - Cool Runnings

### ISSUE THREAD

**Issue by markprycemaher** [sqlcollaborative/DataSaturdays#133]
**Event Name:** Data.Toboggan - Cool Runnings
**Event Date:** Saturday 12 June 2021
**Event Location:** Virtual / Teams
**Event Website:** http://www.datatoboggan.co.uk/
**Sessionize link for CFP** : https://sessionize.com/data-toboggan-cool-runnings
**Sessionize CFP end date:** 16th March
**Youtube link:** https://www.youtube.com/channel/UCXWtt2gXhZEN4_5H7BVPsMQ
**Event Description:**

Azure Synapse Analytics is a practically limitless analytics service that brings together data integration, enterprise data warehousing and big data analytics. Let's spend a day exploring and showcasing these capabilities.

 

It is this analytical power that will help enable any organisation to transform from being reactive into being truly proactive, generating actionable insights that enable both business flow and timely decision-support.

 

We are excited our virtual event  'Cool Runnings' is on Saturday 12 June 2021 and is free to attend.

 

The Call for Speakers is open.  We hope you register and attend the event which covers introductory sessions to in-depth sessions. Enjoy the day!

**Comment by way0utwest** [comment]
@markprycemaher I am thinking to just link to your site for this, unless you want to brand this as a Data Saturday #9 - Data Toboggan Cool Runnings?

**Comment by way0utwest** [comment]
Also, is there a small image (65px) logo?

**Comment by MarkPryceMaherMSFT** [comment]
Lets keep it consistent with the rest of the Data Saturdays: 
Data Saturday #9 - Data Toboggan  - Cool Runnings

**Comment by SQLDBAWithABeard** [comment]
Event page has been created
