### ISSUE TITLE
Trying to upload Sponsors' logos but does not have rights to the asset folder. 

### ISSUE THREAD

**Issue by harrychandrapdx** [sqlcollaborative/DataSaturdays#183]
Since the change to the new format, I am unable to upload the sponsors' logos. Please advise...

Thanks,
Harry

**Comment by spaghettidba** [comment]
Hi Harry, you need to include your files in the PR. Add the files, commit and push to the same branch that you used for the PR. We will see the files in the PR, approve it and it will be fine
