### ISSUE TITLE
Data Saturday Los Angeles

### ISSUE THREAD

**Issue by steverezhener** [sqlcollaborative/DataSaturdays#185]
can you replace our event logo from https://datasaturdays.com/assets/img/events/0007/data.sql_.saturday.jpg
to https://datadriventechnologies.files.wordpress.com/2021/04/sqlsatla.jpg, please?

can you add the following sponsor logos + URLs to the sponsors area, please?
https://datadriventechnologies.files.wordpress.com/2021/04/vmware.png | https://www.vmware.com
https://datadriventechnologies.files.wordpress.com/2021/04/datavail_logo_copy.png | https://www.datavail.com
https://datadriventechnologies.files.wordpress.com/2021/04/wherescape.jpg | https://www.wherescape.com
https://datadriventechnologies.files.wordpress.com/2021/04/sios.png | https://sios.com
https://datadriventechnologies.files.wordpress.com/2021/04/dbwatch-logo.png | https://www.dbwatch.com
https://datadriventechnologies.files.wordpress.com/2021/04/cappuccino-insurance.jpg | https://www.cappuccinoinsurance.com

can you replace the "Organizer: Data Saturday LA" twitter hyperlink from https://datasaturdays.com/2021-06-12-datasaturday0007/ to https://twitter.com/sqlsatla

**Comment by spaghettidba** [comment]
Hey Steve! Have you tried following the wiki? https://github.com/sqlcollaborative/DataSaturdays/wiki/The-data-file

**Comment by steverezhener** [comment]
Unfortunately, I can't figure out how to fork a repository.

**Comment by spaghettidba** [comment]
Hey Steve, please have a look at this PR and see if it's ok. https://github.com/sqlcollaborative/DataSaturdays/pull/190

**Comment by SQLDBAWithABeard** [comment]
Merged
