### ISSUE TITLE
The most important issue

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/DataSaturdays#2]
A test for issue writing but also

Which Version of English are we going to use for this repo. I do not mean the web-site, that will hopefully cater for all but in the wiki, read me etc.

I can cope (more or less thanks to Chrissy) with doing it in US or UK or Aus but I cant cope with UK and US in the same place. 
Thoughts please

**Comment by spaghettidba** [comment]
Honestly, I don't even know what is US and what is UK, except for extra "U"s in UK spelling.

**Comment by SQLDBAWithABeard** [comment]
It's usually the z's that get me :-)

**Comment by potatoqualitee** [comment]
I'm late to the party but I tend to look to others when considering standards  and one thing to note is that Microsoft uses `en-us` as the default for their documentation. I know this applies for SQL Server, and this likely applies to Azure as well though I haven't confirmed.

**Comment by sqlzelda** [comment]
That works. Always nice to learn something new and participate in a world that's larger than the US. (We'll see how I do on my spelling.) :-)

**Comment by SQLDBAWithABeard** [comment]
Closed with color ;-)
