### ISSUE TITLE
Reactivate the XML/RSS feed for new events

### ISSUE THREAD

**Issue by SQLThomas** [sqlcollaborative/DataSaturdays#214]
Can the XML/RSS feed called "Data Saturdays Current Event Feed" that (I think) used to exist at https://datasaturdays.com/events/event.xml please be reactivated?

**Comment by rabryst** [comment]
@SQLThomas Just wanted to let you know we're working on this - it'll be a while yet but thank you for bringing it to our attention.

**Comment by rabryst** [comment]
Probably going to leverage this: https://dzhavat.github.io/2020/01/19/adding-an-rss-feed-to-github-pages.html
