### ISSUE TITLE
List of Sponsors

### ISSUE THREAD

**Issue by sqlworldwide** [sqlcollaborative/DataSaturdays#23]
Will need support for sponsors

- List of sponsors
- Update contact from each sponsor
- Sponsor tier
- During registration option to receive communication from the sponsor (yes/no)

**Comment by Dbakevlar** [comment]
In a meeting the other day, I think it was Janice suggested for virtual events, to have a short, video advertisement to run before the presentation for the vendor who sponsored it.  It's simple, easy and actually makes a virtual session worthwhile investment for a vendor/exhibitor until virtual events become in person again.  I definitely wanted to get that written down before it slipped my mind, as it was such a brilliant suggestion from her.

**Comment by SQLDBAWithABeard** [comment]
There absolutely needs to be a discussion with the sponsors absolutely here, I agree

**Comment by Avahey** [comment]
Maybe the sponsor links could go to a sponsor page on each event, or a single global page for sponsors that help with a lot of events.

**Comment by sqlworldwide** [comment]
We can have a global sponsor on the mail page. But each event will need a local sponsor too.

**Comment by suxstellino** [comment]
Did you guys use the sponsor page of the former SQLsat website? For Parma we're used to make a direct relationship with our local sponsors without using the provided "billing system". @spaghettidba do you know how Marco managed the sponsorship in Pordenone?

About the global sponsors, can we just make a statics web page with logos and share the contacts in a private page to get in touch with them before the event?

This could work for me, but not for everyone, I know. Just asking.

**Comment by amtwo** [comment]
In the States, it varies quite a bit. In major cities/established events, we relied on the SQLSat sponsor "pipeline" less. But smaller & less established events would leverage the sponsor email list more to help hunt for sponsors & funds.

Ex--even if you know the sponsor you want to reach out to, finding the right contact info might not be easy.

**Comment by SQLDBAWithABeard** [comment]
sponsor links and images added to data driven creation #149
