### ISSUE TITLE
New Data Saturday

### ISSUE THREAD

**Issue by WizardDBA** [sqlcollaborative/DataSaturdays#250]
#  Add a New Data Saturday

name - Data Saturday #19 Portugal 2021
date - 2021-12-18 09:30:00
description - Data Saturday #19 Portugal 2021 is a free one-day event for professionals who use the Microsoft data platform.
registrationurl This is your registration URL. You can leave this blank at first and update it later if need be.
scheduleurl - This is your schedule API URL from Sessionize. You can leave this blank until you have it.
sponsors - You can add as many sponsors as you wish or none at all. If there are no sponsors, your site will display a message suggesting that if anyone wishes to sponsor the event to contact you and a link to the contact (see below)
callforspeakers - https://sessionize.com/data-saturday-portugal-2021/
volunteerrequesturl - If you want a link for people to volunteer place it here
organizers - Ivan Campos - https://twitter.com/wizarddba 

# Organisers

Follow the instructions in the wiki to transpose this information into the data files.

**Comment by spaghettidba** [comment]
Hi there! I merged the PR and the event is online. Sorry for the delay
