### ISSUE TITLE
Accessibility & Inclusivity 

### ISSUE THREAD

**Issue by LowlyDBA** [sqlcollaborative/DataSaturdays#27]
This is some slight overlap with #12 , but I think starting from scratch is a huge opportunity to make things as accessible and inclusive as possible (especially digital content). 

Some areas to think about:

* General [ADA website compliance](https://www.revize.com/blog/ada-website-accessibility-guide/) (not legally mandatory likely, but doesn't mean it isn't important)
  * Widgets exist ([EqualWeb](https://www.equalweb.com/html5/?_id=10842&did=1116&G=10842&tab=1) for ex.) that handle a lot of these aspects automagically
  * Standardizing on captioning tools/services on videos (auto-captioning isn't really reliable IMO for those who rely on it)
  * Screen reader compatibility for static content
  * Designs aware of color blindness/deficiencies
* Resources for finding interpreters (primarily thinking ASL/BSL here) for events
* Resources for creating/adapting event spaces in accommodating fashion

**Comment by Dbakevlar** [comment]
Having a set of guidelines for presentation slides for accessibility-  I love Meagan Longoria's recommendations around this.

**Comment by SQLClause** [comment]
This is definately important. Supporting guidelines, reccomended best practices and tools where it's not possible to implement outright.

**Comment by SQLDBAWithABeard** [comment]
This is so good, how do we ensure that these things are in the template?

**Comment by LowlyDBA** [comment]
Brain dump:

I think SQLClause's comment is on the right track - we probably have three top level areas where this can be implemented, with some obvious overlap between them. Most can probably be covered in the CONTRIBUTING doc and/or automated checks as much as possible.

1. Things we can implement and lead by example within the template and main website
2. The CI/CD/repo itself
3. Best practices/guidelines for things people will be creating on their own per event

# Template

## Videos

* In #29 there is mention of a canned intro/outro video and branded videos for specific events
  * Providing closed captioning for these via something like [Amara](https://amara.org/en/) (free) would be an easy way to set a good example + make it easy for anyone to provide additional translations 

## Websites

* Microsoft has a lot of tooling via [Accessibility Insights](https://accessibilityinsights.io/) to meet [Web Content Accessibility Guidelines (WCAG) 2.1 Level AA](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.1&levels=aaa) standards, including a [Github Action](https://github.com/microsoft/accessibility-insights-action) to run scans
* [EqualWeb ](https://www.equalweb.com/html5/?_id=10842&did=1116&G=10842&tab=1)and [UserWay ](https://userway.org/compare)both have free tier widgets that can be layered on top of any site to accomplish a lot of the WCAG standards as well
* Images can be checked for contrast adherence with [ContrastChecker](https://contrastchecker.com/) (maybe a PR checklist item)

## File Templates

### PowerPoint / Slides

* Microsoft has some [ppt accessibility guides](https://support.microsoft.com/en-us/office/make-your-powerpoint-presentations-accessible-to-people-with-disabilities-6f7772b2-2f33-4bd2-8ca7-dae3b2b3ef25) that should apply to any type of  slide templates + we can distill down a rule set in contributor docs

### Markdown

* Markdown by default is pretty great in this area, but a way to enforce alt text on images and links would be ideal (maybe a PR to [markdownlint](https://github.com/DavidAnson/markdownlint) to add a rule for it)

# CI/CD/Repo

* PR Accessibility - [action-accessibility](https://github.com/marketplace/actions/action-accessibility) Github Action replies to PRs with an audio TTS file and an image of the PR's text in [OpenDyslexic](https://opendyslexic.org/) font
* Inclusive Language - [In Solidarity Bot](https://github.com/jpoehnelt/in-solidarity-bot) checks for usage of non-inclusive language (I'm using this now in a project and love it so far)

# Best Practices / Recommendations

## Videos 

* Same as above guidelines for videos - allowing people to add closed captions once the media is uploaded would be great 

## Presentations

* Same as above guidelines for presentation templates

## Websites

* If event websites are going to be clones off this repo, inheriting a lot of the above will be automatic 

## In person events

Unfortunately, a lot of this will probably be country-specific..

* How to find sign language interpreters
  * USA - [Registry of Interpreters for the Deaf](https://myaccount.rid.org/Public/Search/Member.aspx)
  * UK - [Institute of Translation and Interpreting](https://www.iti.org.uk/find-professional-translator-interpreter.html)
  * Other - [European Forum of Sign Language Interpreters](https://efsli.org/links/interpreting-organisations/) has a large listing of various country-specific orgs
* Physical services
  * For USA it would be preferring an [ADA ](https://www.dol.gov/general/topic/disability/ada) (Americans with Disabilities Act) compliant venue or some guidance on how to overcome any shortcomings if the former is not possible

**Comment by SQLDBAWithABeard** [comment]
Hey @LowlyDBA - I love these two suggestions

PR Accessibility - action-accessibility Github Action replies to PRs with an audio TTS file and an image of the PR's text in OpenDyslexic font
Inclusive Language - In Solidarity Bot checks for usage of non-inclusive language (I'm using this now in a project and love it so far)

Do you have any experience of setting them up?

**Comment by andrekamman** [comment]
### Code of Conduct

There is an active Github repo with a good code of conduct specifically for events. It was born out of an event and adapted for many others. We've been using this for Data Saturday in Holland ever since we stopped using the SQLSaturday system years ago.

- It has many contributors and a bunch of translations. 
- It's up to date to modern times and has language regarding gender identity and expression etc. 
- It's been used in a lot of conferences worldwide big and small already. 
- It's easy to use. Fork, remove "this is a template", add conference name and contact details and you're good to go.

I propose we use it : [https://github.com/confcodeofconduct/confcodeofconduct.com](https://github.com/confcodeofconduct/confcodeofconduct.com)
Link to html example in English: [https://en-us.confcodeofconduct.com/](https://en-us.confcodeofconduct.com/)

**Comment by SQLDBAWithABeard** [comment]
I have added the in-solidarity bot

**Comment by amtwo** [comment]
I point folks to that same Code of Conduct @andrekamman, I think it is an excellent one.  It is tailored towards in-person events, so it needs a bit more adjustment when using it for Virtual/online events.

There are really 2 separate scenarios we need a Code of Conduct to cover (or maybe more than 1 Code of Conduct?)
* Contributing to this repo
* In-person events & Online events

We should spin up a dedicated issue for the Code(s) of Conduct discussions. I don't want to detract from the more targeted discussion on Audio/Visual accessibility.

**Comment by SQLDBAWithABeard** [comment]
This add-in was leaving not appropriate links so has been removed
