### ISSUE TITLE
We should make use of the Sessionize API

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/DataSaturdays#3]
Sessionize have built an excellent platform for Speakers, managing call for papers and embedding Agendas

They state

> We think pricing should be fair and simple. All features included in each package. Free for community events with no participation fee

https://sessionize.com/pricing 

I know that it has been used for events such as DataGrillen, Data Scotland and when organising PowerShell Conference Europe we used it also (we had to pay)

Advantages

- One place for speaker abstracts which they control and also works with other events
- Fantastic Call for Speakers experience for organisers 
    - Deals with Acceptance AND declined Emails
    - Easy ranking system, can be used by multiple people at same or different times 

- Super Easy to embed the agenda in and it auto updates and is easily accessed by API for other use cases (Apps etc)

**Comment by Stuart-Moore** [comment]
We use it for relay as well. It needs each event to be checked as ‘not for profit’ rather than the organisation. Which will cause issues if you’re thinking of automating it, though the approval is just an email to support so could still be done.  

And if people want to do paid Precons to raise funds that will probably get in the way unless they do that through another platform.

**Comment by spaghettidba** [comment]
Great point about precons. Honestly, I don't know how much effort it would be to build the session submission / selection / agenda. If we are planning to use their plaform we should probably reach out to them, explain in detail what is the current model and ask what they have to offer.

**Comment by SQLDBAWithABeard** [comment]
Super point about pre-cons - I think that deserves a separate issue and yes reaching out to Sessionize is a brilliant idea.

**Comment by way0utwest** [comment]
Added a more general item on this in #18

**Comment by SQLDBAWithABeard** [comment]
completed #149
