### ISSUE TITLE
Pordenone Event

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/DataSaturdays#32]
Pordenone have reached out to us to ask if we can assist, so @spaghettidba is going to provide something that they can use for their event as we wish to support the community.

It is understood that this will not be perfect or perhaps even vaguely represent what this will be going forward but it will be a starting point which we can iterate from

**Comment by suxstellino** [comment]
We can start with a simple configuration:
- Eventbrite for subscription and mailing of the subscribed
- sessionize for speakers and mailing of speakers
- a simple website (like a wordpress or another website CMS)
I've spoken with @spaghettidba and maybe he can add more details here. 

That's it!

**Comment by benkettner** [comment]
I'd be more than happy to contribute. I know some wordpress, some drupal and some php - so anything to get this up and running.... 
I would suggest to start with wordpress and if needs be migrate at a later point. For eventbrite there is a simple plugin to display your events: https://wordpress.org/plugins/widget-for-eventbrite-api/ - however that requires the organizers to create the events in Eventbrite afaik, we could look for another plugin where event creation can be done from WP or write an extension ourselves that should not be too hard as the eb-api is quite well documented https://www.eventbrite.com/platform/api

For Sessionize: we would only need to embed the schedule from Sessionize in Wordpress, that is fairly easy as there is alreay a WP plugin: https://sessionize.com/developers

I'd suggest to start with a small docker-compose for local development, should we include this in this repo or create a new repo for sakes of clarity?

**Comment by EmanueleMeazzo** [comment]
Count me in for any additional help you may need, of course 👍

**Comment by ddominici** [comment]
Needless to say, but count me in to help with the organization.

**Comment by SQLDBAWithABeard** [comment]
event page created, event held :D
