### ISSUE TITLE
Support for virtual events

### ISSUE THREAD

**Issue by hsavran** [sqlcollaborative/DataSaturdays#33]
Easy access to virtual event urls and options.

**Comment by SQLDBAWithABeard** [comment]
Can you expand a little on this. What additional requirements are there for virtual events?

**Comment by wolfgangstrasser** [comment]
What I could imagine:
* URLs for specific tracks (team meeting links, GoToWebinar links ...)

**Comment by SQLDBAWithABeard** [comment]
completed with #149
