### ISSUE TITLE
Short Term Guidance for SQL Saturdays

### ISSUE THREAD

**Issue by way0utwest** [sqlcollaborative/DataSaturdays#39]
As of  20  Dec 2020, there are six events in flight. I am ignoring Albuquerque and Orlando as they are too far out.

These events need support and help to run. As they are virtual, I think the resources are minimal, but we need something. I have sent this to one organizer already, but welcome comments. The main items needed are:

1. Speaker CFP, approval, and scheduling
2. email to attendees and speakers
3. Ticketing (not sure how important this is)
4. landing page on web for marketing, redirect to broadcast, registration, CFP, etc.
5. Broadcast

My advice:

1.	Move to Sessionize for speakers immediately. Datasaturdays (or something) will likely support or use this service.
2.	Move to Mailchimp for your email needs. A number of non-pass events have used this. Email your existing speakers/registrants/volunteers to join a list there. (free for 2000 - https://mailchimp.com/pricing/)
3.	Eventbrite might work if you want ticketing, but for your event being virtual, I’d just email everyone in your mailchijp list. Once we get back to live events, we will hope to be providing something else
4.	We will provide a landing page for you at datasaturdays.com for now (https://datasaturdays.com/events/datasaturday0001.html ). We can update that with your schedule, speakers, etc.
5.	Broadcast – I am sure I can find someone to pay for zoom or teams or something in the next month, but if you need it, youtube broadcasting might be the simplest thing to plan for how.

Any other advice or things I've missed are appreciated.

**Comment by benkettner** [comment]
We should get in touch with Wolfgang Strasser for his Austrian event. They are on Jan 15th and have real problems right now because they can't even get the message to the SQL Sat website that they are still going to have the event.

**Comment by EmanueleMeazzo** [comment]
Not something for the super short term I guess, but for streaming we can eventually evaluate some platform like [Restream](https://restream.io/pricing) to stream to multiple social networks at the same time

**Comment by wolfgangstrasser** [comment]
#SQLSatVienna news update - we are on track!
* I tried to update the SQLSat page -> this did not work: BUT I could send an email yesterday using the SQLSaturday admin page. 
* We are currently creating an Eventbrite event to move the attendees there (we can send them emails)
* plus: we are moving to Teams meetings 
* Schedule will be placed on an independent webpage (that we have a fallback whenever SQLSaturday.com will not work anymore)
