### ISSUE TITLE
I want to register a new event - What do I do?

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/DataSaturdays#41]
To create a new event - Please follow the process in the Wiki - https://github.com/sqlcollaborative/DataSaturdays/wiki

**Comment by coolsekali** [comment]
On behalf of the Redmond SQL User Group, I would like to reserve Data Saturday Redmond for April 3rd, 2021. 

Thanks to @SQLDBAWithABeard for starting this thread.

**Comment by SQLDBAWithABeard** [comment]
I have received an email from the New York team - So I am leaving it here for reference.

NYC has no date yet (we need the MS office to open before we can do anything) but I can commit that we will use DataSaturday  model

=tg=

**Comment by sqlworldwide** [comment]
If I can secure the Microsoft office in Burlington MA, USA we will for sure hold a full-day event. We have been using this venue for many years, so it is a matter of Microsoft open the space for user groups.

**Comment by way0utwest** [comment]
For now, I have a project for "Events" and I have added an Issue for each event. I will add the Redmond event as well as the Vienna one, as they have requested help.

To date, we have a static page for events, though we need to expand on that.

**Comment by way0utwest** [comment]
@harrychandrapdx Issue at #58 for you to add details to. We can then build a page for you

**Comment by way0utwest** [comment]
You can also register here to attract speakers: https://callfordataspeakers.com/
