### ISSUE TITLE
CI/CD - automated event creation without manual input

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/DataSaturdays#42]
To enable simple easy automated event creation without manual input

Right now, we have GitHub actions which will deploy the website on a new commit to master.

There is a lot missing from the rest of the process. But we are in a good place to start the way we want to go on

https://twitter.com/mipsytipsy/status/1340958240184516611?s=20

I'll start a list, please add to it.

- Automated Testing

**Comment by gavincampbell** [comment]
Are you planning to use the PR mechanism for "approving" new events?  This would fit in with #4 , assuming Jekyll, Hugo, or similar, so a requester could preview the site with their changes locally, then create a PR to add their event to the public site.

**Comment by gavincampbell** [comment]
OK, I wasn't paying attention, there's already a Jekyll site!

**Comment by LowlyDBA** [comment]
@gavincampbell  I think that is still a good (open-ish) question. So far it looks like we're semi-manually or manually generating individual pages, which is going to start adding some tech debt to cleanup once we standardize and need to go back and change things.

I think one of the first things to decide on is Jekyll, Hugo, Vuepress, etc. so that we can start building out stuff The Right Way ™️ . 

@SQLDBAWithABeard can you convert this to a discussion also?

**Comment by way0utwest** [comment]
I think we need something. I added events 2, 3, (and 4, 5 today), but I'm manually editing things. Some of that is fine, but over time, we need a better solution.

- assign number somehow
- automated test - check date against event brite
- automated test - validate links do not return 404
- automated test - if no link for speakers, include coming soon
- automated test - if no link for registration, coming soon
- check an email contact is listed.

I don't care what type of site. Static is likely completely fine for now, so we need a platform. I have no opinion here, as I haven't used any. I am going to try a Jekyll site and experiment, but it's something we need to have a proposal from someone as to why to pick a particular platform (pros/cons, example of new page) and then call a vote.

**Comment by SQLDBAWithABeard** [comment]
First iteration completed with #149
