### ISSUE TITLE
Event numbering

### ISSUE THREAD

**Issue by MichaelAdrianJohnson** [sqlcollaborative/DataSaturdays#43]
Should we new try and continue the numbering from the SQL Saturday site, that way if we are able to get the SQLSaturday.com brand (Like @way0utwest is tying to do) then we can merge the two streams pretty easily? 
~The highest published event I saw was 1023.

**Comment by amtwo** [comment]
While DataSaturdays are built to pick up where SQLSaturday ends, I think there is some important symbolism in having a "fresh start" at 0001. DataSaturdays are _not_ a continuation of SQLSaturday, but rather a new/reborn data event that is filling a void. 

Additionally, the SQLSaturday brand may be bought out of bankruptcy by someone who chooses to continue with those events--the lack of transparency here means the community can't wait & see if SQLSaturday will continue in an acceptable way. If SQLSaturday & Data Saturdays were to _both_ be running concurrently, and using same number space it will cause brand confusion between the two, which we can avoid by starting fresh at 0001.

**Comment by SQLDBAWithABeard** [comment]
Would it be ok to close this issue and concentrate this discussion in #28 ? to keep conversations together?

**Comment by MichaelAdrianJohnson** [comment]
Sure thing
