### ISSUE TITLE
Data Saturday #1 - Pordeone

### ISSUE THREAD

**Issue by way0utwest** [sqlcollaborative/DataSaturdays#52]
Open issue for the first event and any support needs they may have. 

Page is already up: [Data Saturday #1 - Pordeone](https://datasaturdays.com/events/datasaturday0001.html)

PR for the page: https://github.com/sqlcollaborative/DataSaturdays/pull/35

If there are any needs, please list them in comments below.

**Comment by amtwo** [comment]
This looks like a duplicate for #32.  @way0utwest Not sure if you wanted to have a fresh start with this issue, or just didn't notice the other one. We should close out one of them

**Comment by way0utwest** [comment]
Yep, dup, closing
