### ISSUE TITLE
Data Saturday Guatemala 2021

### ISSUE THREAD

**Issue by way0utwest** [sqlcollaborative/DataSaturdays#53]
This is the issue for the Data Saturday in Guaemala

- [EventBrite](https://www.eventbrite.com/e/data-saturday-guatemala-2021-tickets-133805653311) 
- [Sessionize](https://sessionize.com/data-saturday-guatemala-2021/)

A number and page are needed. 

Any support requests, please comment below.

**Comment by SQLDBAWithABeard** [comment]
This has been published with PR #64
