### ISSUE TITLE
Guidlines for Making Decisions

### ISSUE THREAD

**Issue by way0utwest** [sqlcollaborative/DataSaturdays#56]
As this is a group community project, and I have seen decisions being made, issues closed, etc., I am concerned that we may not be considering how opinions and views may diverge on issues, especially over time. I realize the early days will be different than things may move over time.

I would propose that we have a motion and second to close issues (or advance them) to a vote, with 2-3 positive votes advancing an issue and 3 negative votes delaying it.

We can always change course or reverse actions, but having a process of some sort would be valuable.

**Comment by SQLDBAWithABeard** [comment]
At present the admins for this repository are

@rabryst          Randolph West 
@way0utwest	Steve Jones 
@SQLDBAWithABeard	Rob Sewell 
@spaghettidba Gianluca Sartori 
@amtwo	        Andy Mallon (ᴀᴍ²) 
@sqlzelda	Elizabeth Noble
@sqlespresso	Monica Rathbun 
@SQLClause	Johan Ludvig Brattås 
@sqlatspeed	Matt Gordon

There is still no representation in this list for people in South America, Asia or Australasia. 

I would hope that we can bring more people from those areas, with more diverse experience and knowledge to bring this forward in a more inclusive manner. As an example, the current website is available in English only.

This list is simply the people who have shown an initial interest.
These are the people who have the control to

- Administer the repository
- Approve Pull Requests

Right now that is all.

We must be careful to continue to enable agile delivery without impacting it with too much process.

If we are to have a vote before moving forward with any issues, Who votes? How long does the vote stay open? There are many questions to be answered here.

**Comment by SQLDBAWithABeard** [comment]
At present the admins for this repository are

@rabryst          Randolph West 
@way0utwest	Steve Jones 
@SQLDBAWithABeard	Rob Sewell 
@spaghettidba Gianluca Sartori 
@amtwo	        Andy Mallon (ᴀᴍ²) 
@sqlzelda	Elizabeth Noble
@sqlespresso	Monica Rathbun 
@SQLClause	Johan Ludvig Brattås 
@sqlatspeed	Matt Gordon

There is still no representation in this list for people in South America, Asia or Australasia. 

I would hope that we can bring more people from those areas, with more diverse experience and knwoledge to bring this forward

This list is simply the people who have shown an initial interest.
These are the people who have the control to

- Administer the repository
- Approve Pull Requests

Right now that is all.

We must be careful to continue to enable agile delivery without impacting it with too much process.

If we are to have a vote before moving forward with any issues, Who votes? How long does the vote stay open? There are many questions to be answered here.

**Comment by SQLDBAWithABeard** [comment]
Could this be closed and moved to the discussions?

I have set up discussions on the repo and the link is here

https://github.com/sqlcollaborative/DataSaturdays/discussions

also available on the front page

**Comment by rabryst** [comment]
Moved to Discussions section
