### ISSUE TITLE
Data Saturday Redmond

### ISSUE THREAD

**Issue by way0utwest** [sqlcollaborative/DataSaturdays#58]
requesting details from organizers.

**Comment by harrychandrapdx** [comment]
Hi, thank you @way0utwest for creating the issue! 

Is it possible to request Data Saturday Redmond as Data Saturday #5? 

Here's the info of the event so far. I will update with the links as available. 

Event name: Data Saturday Redmond
Event Date: April 3rd, 2021
Event location: Virtual
Sessionize link for CFP: TBD
Eventbrite for attendees: TBD

Admin contact: DataSaturday2021@redmondsql.org 

-- Harry

**Comment by SQLDBAWithABeard** [comment]
This has been published with PR #75
