### ISSUE TITLE
Start using Discussions

### ISSUE THREAD

**Issue by LowlyDBA** [sqlcollaborative/DataSaturdays#61]
Given the preliminary state of DataSaturdays, I think it would be beneficial to enable [Github Discussions](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions) on this repo so that high level brainstorming / discussions can happen there and subsequently allow Issues to remain focused on specific action items that can be tied to a PR.

**Comment by SQLDBAWithABeard** [comment]
This is an excellent idea and could enable us to focus on the difficult task of building something cool that works and leave other discussions in a different place

I cannot do this from my phone but I will take a look

**Comment by m82labs** [comment]
My recent issue would certainly fall into this category, I had no idea such a feature existed.

**Comment by SQLDBAWithABeard** [comment]
I have set up discussions on the repo and the link is here

https://github.com/sqlcollaborative/DataSaturdays/discussions

also available on the front page

Can I leave this issue open fro 24 hours and then close @LowlyDBA ?
