### ISSUE TITLE
Haiti event - 27 March 2021

### ISSUE THREAD

**Issue by rabryst** [sqlcollaborative/DataSaturdays#68]
Their leader Jean Joseph has already created a Sessionize link for the rebadged Haiti SQLSaturday and I offered to promote it here as well. https://sessionize.com/HaitianSQLOneDayEvent

Here is the Eventbrite link as well: https://www.eventbrite.com/e/haitian-sql-one-day-event-tickets-133876158193

**Comment by way0utwest** [comment]
Adding a page for this, assigning event number 3

**Comment by SQLDBAWithABeard** [comment]
This has been published with PR #70
