### ISSUE TITLE
Johannesburg Event - 13 March 2021

### ISSUE THREAD

**Issue by MichaelAdrianJohnson** [sqlcollaborative/DataSaturdays#71]
Data Saturday Johannesburg 2021

Provisional links to speaker submission and event here:
https://sessionize.com/data-saturday-johannesburg/?e=e0483b
https://www.eventbrite.com/e/data-saturday-johannesburg-2011-tickets-134437071901
~Links will change when event goes live

This will be an online only event, both because its the right thing to do right now and Microsoft our usual venue sponsor do not allow in-person events at the moment.

**Comment by way0utwest** [comment]
Working on this with number 4

**Comment by way0utwest** [comment]
Confirming: Organizer: Michael  Johnson
Event Date: Mar 13
Text: Not much on the Eventbrite page, so leave a note if you want more.
Sponsors: Let me know logos when you can.
Email: how to contact you (you can twitter me a DM)

**Comment by way0utwest** [comment]
Also, EventBrite has 2011 as the date.

**Comment by MichaelAdrianJohnson** [comment]
> Also, EventBrite has 2011 as the date.

Some of us have a hard time letting go :-)
I've fixed up the  date on the site and will build out the Eventbrite site  over the next few days (It only goes live on the 1st)

**Comment by SQLDBAWithABeard** [comment]
This has been published with PR #75
