### ISSUE TITLE
Data Saturday Malta

### ISSUE THREAD

**Issue by DennesTorres** [sqlcollaborative/DataSaturdays#82]
Hi,

Could you include the Data Saturday Malta on the website, please? The links are:

EventBrite: https://www.eventbrite.com/e/malta-data-saturday-2021-tickets-135044412473
Sessionize: https://sessionize.com/malta-data-saturday-2021/
My E-mail: dennes@bufaloinfo.com.br

It's for 24/04

**Comment by way0utwest** [comment]
Tackling with a new page a PR

**Comment by SQLDBAWithABeard** [comment]
Malta event page created
