### ISSUE TITLE
Events order

### ISSUE THREAD

**Issue by MikeyBronowski** [sqlcollaborative/DataSaturdays#87]
Currently looks like that events order is by event id, rather than date:

![image](https://user-images.githubusercontent.com/13431760/103626902-c2cc6180-4f34-11eb-92cf-538ead62cc47.png)

**Comment by spaghettidba** [comment]
I would like to solve the order of events in the page using a sortable table, by deafult sorted dy date ascending. We're not there yet, but we are planning some code changes to generate the site from a json source and only include new events (not past ones) and sort by date.

**Comment by spaghettidba** [comment]
Solved the dynamic table with sorting
