### ISSUE TITLE
Guatemala event: date?

### ISSUE THREAD

**Issue by HugoKornelis** [sqlcollaborative/DataSaturdays#89]
The Guatemala event is listed with date March 27 on the event list at datasaturdays.com. But the event page itself (https://datasaturdays.com/events/datasaturday0002.html) as well as the sessionize page (https://sessionize.com/data-saturday-guatemala-2021/) list January 23.

Please verify which is correct and change the wrong dates accordingly.

**Comment by spaghettidba** [comment]
Fixed
