### ISSUE TITLE
Data Saturday Los Angeles

### ISSUE THREAD

**Issue by steverezhener** [sqlcollaborative/DataSaturdays#92]
event name - Data Saturday Los Angeles
event date - 06/12/2021
event location, if physical - Virtual
description of your event, including multiple languages, if applicable. - SQL Saturday in Los Angeles
SQLSaturday is a free training event for professionals who use the Microsoft/AWS/GCP data platforms. These community events offer content across data management, cloud and hybrid architecture, analytics, business intelligence, AI, and more.
Sessionize link for CFP - https://t.co/0SFdedqp3u
Eventbrite (or other registration ) link - https://t.co/lYgwzAvRSe
contact information - sqlsatla at datadriventechnologies.org

**Comment by way0utwest** [comment]
Can the sessionize and eventbrite be amended to say Data Saturday?

**Comment by steverezhener** [comment]
@way0utwest , done. Replaced SQL Saturday with Data/SQL Saturday.

**Comment by steverezhener** [comment]
please allow the contact organizer name to be custom. for our event, i would like visitors to see SQL Saturday in LA instead of my name.

**Comment by way0utwest** [comment]
PR merged to fix the organizer name: https://datasaturdays.com/events/datasaturday0007.html

**Comment by steverezhener** [comment]
Please add the following:

1. our event logo - https://datadriventechnologies.files.wordpress.com/2021/02/data.sql_.saturday.jpg?resize=219%2C219
2. link to volunteer sign up form - https://datadriventechnologies.org/2021/02/22/2021-data-sql-saturday-call-to-volunteers/
3. link to sponsorship plan - https://datadriventechnologies.org/2021/02/22/2021-data-sql-saturday-sponsorship-plan/

**Comment by way0utwest** [comment]
PR submitted #136

**Comment by SQLDBAWithABeard** [comment]
Event page has been created
